version: "2"

run:
  timeout: 5m
  go: '1.16'

linters:
  disable-all: true
  enable:
    - staticcheck
    - govet
    - ineffassign
  disable:
    - errcheck

linters-settings:
  staticcheck:
    checks: ["all"]
