version: "2"

linters:
  enable:
    - staticcheck
    - govet      # Included by default in 'go vet'
    - errcheck   # Check for unchecked errors
    - ineffassign # Detects unused assignments
  disable-all: true

run:
  timeout: 5m

linters-settings:
  staticcheck:
    checks: ["all"]
