version: 2.1.6
linters:
  enable:
    - staticcheck
    - govet      # Included by default in 'go vet'
    - errcheck   # Check for unchecked errors
    - ineffassign # Detects unused assignments
    - typecheck  # Go type checker
  disable-all: true

linters-settings:
  staticcheck:
    checks: ["all"]

run:
  timeout: 5m
