version: 2

run:
  go: '1.16'  # Minimum Go version from go.mod
  timeout: 5m

linters:
  enable:
    - staticcheck
    - govet      # Included by default in 'go vet'
    - errcheck   # Check for unchecked errors
    - ineffassign # Detects unused assignments
  disable-all: true

issues:
  exclude-rules:
    - linters: [typecheck]
      path: "."

linters-settings:
  staticcheck:
    checks: ["all"]
